const REPO='https://github.com/mahsa-teimourikia/agent-identity';
const LESSONS=[
{level:'beginner',step:1,title:'Identity context and principals',summary:'Build a trustworthy request context from issuer, subject, tenant, audience, scopes, and expiry.',detail:'You will distinguish human, workload, and delegated identities, then reject an expired or cross-tenant credential before a tool call.',material:`${REPO}/blob/main/docs/identity-and-authorization.md#identity-primitives`,lab:`${REPO}/blob/main/labs/beginner/01_identity_context.py`,run:'python3 labs/beginner/01_identity_context.py',notebook:`${REPO}/blob/main/labs/notebooks/01_identity_context.ipynb`,q:['Which claim identifies the intended API?',['audience','email','prompt'],0,'Audience binding prevents replay at another API.']},
{level:'beginner',step:2,title:'Deny-by-default authorization',summary:'Use explicit actions, narrow tools, and approval for destructive work.',detail:'Start with an allow-list: unknown roles and actions fail closed, while irreversible actions require a separate approval signal.',material:`${REPO}/blob/main/docs/identity-and-authorization.md#authorization-models`,lab:`${REPO}/blob/main/labs/beginner/02_authorization_basics.py`,run:'python3 labs/beginner/02_authorization_basics.py',q:['What should an unknown action do?',['Allow','Deny and audit','Ask the model'],1,'Policy boundaries fail closed.']},
{level:'intermediate',step:3,title:'OAuth scopes and token exchange',summary:'Down-scope a parent grant for one downstream audience.',detail:'Exchange a broad grant for a shorter-lived child token. The implementation proves requested scopes are contained by the parent.',material:`${REPO}/blob/main/docs/identity-and-authorization.md#oauth-exchange-and-proof-of-possession`,lab:`${REPO}/blob/main/labs/intermediate/01_token_exchange.py`,run:'python3 labs/intermediate/01_token_exchange.py',notebook:`${REPO}/blob/main/labs/notebooks/02_token_exchange.ipynb`,q:['A child token may contain…',['any requested scope','only scopes contained by its parent','all tenant scopes'],1,'Delegation cannot add authority.']},
{level:'intermediate',step:4,title:'ABAC, ReBAC, risk, and approval',summary:'Combine tenant, relationship, action, and risk attributes.',detail:'Move beyond roles: enforce tenant isolation and team relationships, then require step-up approval for high-risk writes.',material:`${REPO}/blob/main/docs/identity-and-authorization.md#authorization-models`,lab:`${REPO}/blob/main/labs/intermediate/02_policy_engine.py`,run:'python3 labs/intermediate/02_policy_engine.py',q:['Risk can trigger…',['step-up approval','scope escalation','permanent credentials'],0,'Risk gates sensitive actions.']},
{level:'advanced',step:5,title:'Multi-agent delegation contracts',summary:'Use typed, bounded envelopes across agent-to-agent hops.',detail:'Pass a typed delegation instead of a bearer token; intersect scopes, bind the audience, and cap chain depth to prevent laundering.',material:`${REPO}/blob/main/docs/identity-and-authorization.md#delegation-and-multi-agent-boundaries`,lab:`${REPO}/blob/main/labs/advanced/01_delegation_chain.py`,run:'python3 labs/advanced/01_delegation_chain.py',q:['What limits delegation laundering?',['unbounded hops','scope intersection and depth limits','forwarding bearer tokens'],1,'Bounded delegation prevents transitive privilege growth.']},
{level:'advanced',step:6,title:'Audit, revocation, and incidents',summary:'Operate identity with evidence, rotation, and a kill switch.',detail:'Create structured audit events and contain a compromised token without waiting for a redeploy.',material:`${REPO}/blob/main/docs/identity-and-authorization.md#production-checklist`,lab:`${REPO}/blob/main/labs/advanced/02_audit_and_incident.py`,run:'python3 labs/advanced/02_audit_and_incident.py',q:['Why store a policy version?',['to reproduce the decision','to store secrets','to widen access'],0,'Versioned policy makes decisions explainable.']}
];
